name: github_analyzer
description: "Analyze GitHub repositories and generate AI context for LLMs"
version: 0.0.3

homepage: https://github.com/cruxhan/github_analyzer
repository: https://github.com/cruxhan/github_analyzer
issue_tracker: https://github.com/cruxhan/github_analyzer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.0
  crypto: ^3.0.3
  dio: ^5.4.3+1
  dotenv: ^4.2.0
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.9
  mockito: ^5.4.4
  test: ^1.25.2