// lib/src/common/constants.dart

const List<String> kDefaultExcludePatterns = [
  // Version Control Systems
  '.git',
  '.git/**',
  '.svn',
  '.svn/**',
  '.hg',
  '.hg/**',
  '.bzr',
  '.bzr/**',
  'CVS',
  'CVS/**',
  '.cvsignore',

  // Flutter/Dart Platform Directories
  'android',
  'android/**',
  'ios',
  'ios/**',
  'windows',
  'windows/**',
  'linux',
  'linux/**',
  'macos',
  'macos/**',
  'web',
  'web/**',

  // Build Outputs & Artifacts
  'build',
  'build/**',
  'dist',
  'dist/**',
  'out',
  'out/**',
  'target',
  'target/**',
  'bin',
  'bin/**',
  'obj',
  'obj/**',
  '.dart_tool',
  '.dart_tool/**',
  '.flutter-plugins',
  '.flutter-plugins-dependencies',
  '.metadata',
  '.packages',

  // Dependencies & Package Managers
  'node_modules',
  'node_modules/**',
  '.pub-cache',
  '.pub-cache/**',
  '.gradle',
  '.gradle/**',
  'vendor',
  'vendor/**',
  'packages',
  'packages/**',
  'bower_components',
  'bower_components/**',
  'jspm_packages',
  'jspm_packages/**',
  '.pnpm-store',
  '.pnpm-store/**',
  '.yarn',
  '.yarn/**',
  '.npm',
  '.npm/**',

  // IDE & Editors
  '.idea',
  '.idea/**',
  '.vscode',
  '.vscode/**',
  '.fleet',
  '.fleet/**',
  '.vs',
  '.vs/**',
  '.eclipse',
  '.eclipse/**',
  '.settings',
  '.settings/**',
  '.project',
  '.classpath',
  '.c9',
  '.c9/**',
  '*.code-workspace',
  '*.sublime-project',
  '*.sublime-workspace',
  '*.code-workspace',
  '.atom',
  '.atom/**',

  // JetBrains IDEs specific
  '*.iml',
  '*.ipr',
  '*.iws',
  '.idea_modules',
  '.idea_modules/**',

  // Test & Coverage
  'coverage',
  'coverage/**',
  '.nyc_output',
  '.nyc_output/**',
  'test_driver',
  'test_driver/**',
  'integration_test',
  'integration_test/**',
  '.pytest_cache',
  '.pytest_cache/**',
  'htmlcov',
  'htmlcov/**',
  '.tox',
  '.tox/**',
  '.coverage',
  '.coverage.*',
  'nosetests.xml',
  'coverage.xml',
  '*.cover',
  '.hypothesis',
  '.hypothesis/**',

  // Generated Files (Flutter/Dart)
  '**/*.g.dart',
  '**/*.freezed.dart',
  '**/*.gr.dart',
  '**/*.config.dart',
  '**/*.pb.dart',
  '**/*.pbenum.dart',
  '**/*.pbgrpc.dart',
  '**/*.pbjson.dart',
  '**/*.mocks.dart',
  '**/*.gen.dart',
  '**/*.graphql.dart',
  '**/*.gql.dart',
  '**/*.chopper.dart',
  '**/*.drift.dart',

  // Lock Files
  '*.lock',
  'pubspec.lock',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'Cargo.lock',
  'Gemfile.lock',
  'poetry.lock',
  'composer.lock',
  'Pipfile.lock',
  'go.sum',
  'mix.lock',

  // Log Files
  '*.log',
  '*.log.*',
  'logs',
  'logs/**',
  'npm-debug.log*',
  'yarn-debug.log*',
  'yarn-error.log*',
  'pnpm-debug.log*',
  'lerna-debug.log*',

  // System Files (macOS)
  '.DS_Store',
  '._*',
  '.Spotlight-V100',
  '.Trashes',
  '.AppleDouble',
  '.LSOverride',
  '.DocumentRevisions-V100',
  '.fseventsd',
  '.TemporaryItems',
  '.VolumeIcon.icns',
  '.com.apple.timemachine.donotpresent',
  '.AppleDB',
  '.AppleDesktop',
  'Network Trash Folder',
  'Temporary Items',
  '.apdisk',
  '__MACOSX',
  '__MACOSX/**',

  // System Files (Windows)
  'Thumbs.db',
  'Thumbs.db:encryptable',
  'ehthumbs.db',
  'ehthumbs_vista.db',
  'Desktop.ini',
  '\$RECYCLE.BIN',
  '\$RECYCLE.BIN/**',
  '*.cab',
  '*.msi',
  '*.msix',
  '*.msm',
  '*.msp',
  '*.lnk',

  // System Files (Linux)
  '*~',
  '.directory',
  '.Trash-*',
  '.nfs*',

  // Temporary & Cache
  'tmp',
  'tmp/**',
  'temp',
  'temp/**',
  '.cache',
  '.cache/**',
  '__pycache__',
  '__pycache__/**',
  '*.pyc',
  '*.pyo',
  '*.pyd',
  '.Python',
  'pip-log.txt',
  'pip-delete-this-directory.txt',
  '.mypy_cache',
  '.mypy_cache/**',
  '.dmypy.json',
  'dmypy.json',

  // Backup Files
  '*.bak',
  '*.backup',
  '*.swp',
  '*.swo',
  '*.swn',
  '*.swm',
  '*~',
  '*.orig',
  '*.rej',
  '*.tmp',
  '*.old',
  '*.save',

  // JavaScript/TypeScript/Node Build Outputs
  '**/*.min.js',
  '**/*.min.css',
  '*.bundle.js',
  '*.chunk.js',
  '*.map',
  '.next',
  '.next/**',
  '.nuxt',
  '.nuxt/**',
  '.vuepress/dist',
  '.vuepress/dist/**',
  '.serverless',
  '.serverless/**',
  '.fusebox',
  '.fusebox/**',
  '.dynamodb',
  '.dynamodb/**',
  '.parcel-cache',
  '.parcel-cache/**',
  '.turbo',
  '.turbo/**',
  '.vercel',
  '.vercel/**',
  '.netlify',
  '.netlify/**',

  // Environment & Secrets
  '.env',
  '.env.*',
  '.envrc',
  'venv',
  'venv/**',
  'env',
  'env/**',
  'ENV',
  'ENV/**',
  'virtualenv',
  'virtualenv/**',
  '.venv',
  '.venv/**',
  'credentials.json',
  'secrets.json',
  'secret.yaml',
  'secrets.yaml',
  '*.key',
  '*.pem',
  '*.p12',
  '*.pfx',
  '*.jks',
  '*.keystore',
  '.aws',
  '.aws/**',
  '.gcp',
  '.gcp/**',

  // CI/CD
  '.github/workflows/.artifacts',
  '.github/workflows/.artifacts/**',
  '.gitlab-ci-local',
  '.gitlab-ci-local/**',
  '.circleci/cache',
  '.circleci/cache/**',
  'jenkins.xml',
  '.travis',
  '.travis/**',

  // Docker
  '.dockerignore',
  'docker-compose.override.yml',
  '.docker',
  '.docker/**',

  // Documentation Build
  'doc/api',
  'doc/api/**',
  'docs/_build',
  'docs/_build/**',
  'docs/.vuepress/dist',
  'docs/.vuepress/dist/**',
  'site',
  'site/**',
  '_site',
  '_site/**',
  '.jekyll-cache',
  '.jekyll-cache/**',
  '.sass-cache',
  '.sass-cache/**',

  // Binary & Large Files
  '*.exe',
  '*.dll',
  '*.so',
  '*.so.*',
  '*.dylib',
  '*.class',
  '*.war',
  '*.ear',
  '*.jar',
  '*.rar',
  '*.zip',
  '*.tar',
  '*.tar.gz',
  '*.tgz',
  '*.7z',
  '*.dmg',
  '*.iso',
  '*.apk',
  '*.app',
  '*.ipa',
  '*.aab',
  '*.dex',
  '*.ap_',
  '*.o',
  '*.obj',
  '*.a',
  '*.lib',

  // Media Files (optional - adjust based on needs)
  '**/*.mp4',
  '**/*.mov',
  '**/*.avi',
  '**/*.mkv',
  '**/*.mp3',
  '**/*.wav',
  '**/*.flac',

  // Font Files
  '**/*.ttf',
  '**/*.otf',
  '**/*.woff',
  '**/*.woff2',
  '**/*.eot',

  // Firebase
  'firebase_options.dart',
  '.firebase',
  '.firebase/**',
  'firebase-debug.log',
  'firestore-debug.log',
  'ui-debug.log',
  'firestore.rules',
  'storage.rules',

  // Native Platform Additional (Flutter specific)
  'Pods',
  'Pods/**',
  'Podfile.lock',
  'xcuserdata',
  'xcuserdata/**',
  'DerivedData',
  'DerivedData/**',
  '*.xcworkspace',
  '*.xcodeproj',
  'project.xcworkspace',
  'project.xcworkspace/**',
  'local.properties',
  'GeneratedPluginRegistrant.*',
  '*.iml',
  '*.hprof',
  '.externalNativeBuild',
  '.externalNativeBuild/**',
  '.cxx',
  '.cxx/**',
  'captures',
  'captures/**',

  // Android Gradle specific
  '.gradle-cache',
  '.gradle-cache/**',
  'gradle-app.setting',
  'gradlew',
  'gradlew.bat',
  'gradle/wrapper',
  'gradle/wrapper/**',
  '*.apk',
  'output.json',

  // iOS specific
  '*.ipa',
  '*.dSYM.zip',
  '*.dSYM',
  '*.dSYM/**',
  'timeline.xctimeline',
  'playground.xcworkspace',
  'playground.xcworkspace/**',

  // Symbolic Links & Special Files
  '**/.*.swp',
  '**/.*.swo',
  '**/core',
  '**/core.*',

  // Database Files
  '*.db',
  '*.sqlite',
  '*.sqlite3',
  '*.db-shm',
  '*.db-wal',
  '*.db-journal',

  // Terraform
  '.terraform',
  '.terraform/**',
  '*.tfstate',
  '*.tfstate.*',
  '.terraform.lock.hcl',

  // Kubernetes
  '*.kubeconfig',

  // Miscellaneous
  '*.pid',
  '*.seed',
  '*.pid.lock',
  '.eslintcache',
  '.stylelintcache',
  '.rpt2_cache',
  '.rpt2_cache/**',
  '.yarn/cache',
  '.yarn/cache/**',
  '.yarn/unplugged',
  '.yarn/unplugged/**',
  '.yarn/build-state.yml',
  '.yarn/install-state.gz',
  '.pnp.*',
  'tsconfig.tsbuildinfo',
  '.rush',
  '.rush/**',
  'lerna-debug.log',

  // Monorepo tools
  '.nx',
  '.nx/**',
  '.turbo',
  '.turbo/**',

  // Static analysis
  '.scannerwork',
  '.scannerwork/**',
  '.sonar',
  '.sonar/**',

  // Rust
  'Cargo.lock',
  'target',
  'target/**',

  // Go
  'go.work',
  'go.work.sum',

  // Ruby
  '.bundle',
  '.bundle/**',

  // Elixir
  '_build',
  '_build/**',
  'deps',
  'deps/**',

  // Jupyter Notebooks
  '.ipynb_checkpoints',
  '.ipynb_checkpoints/**',

  // R
  '.Rproj.user',
  '.Rproj.user/**',
  '.Rhistory',
  '.RData',
  '.Ruserdata',

  // Large Language Models & AI
  '*.onnx',
  '*.pb',
  '*.h5',
  '*.hdf5',
  '*.safetensors',
  '*.bin',
  'models',
  'models/**',
  'checkpoints',
  'checkpoints/**',

  // Game Development (Unity, Unreal)
  'Library',
  'Library/**',
  'Temp',
  'Temp/**',
  '*.csproj',
  '*.unityproj',
  '*.sln',
  '*.suo',
  '*.user',
  '*.userprefs',
  '*.pidb',
  '*.booproj',
  'sysinfo.txt',

  // Xcode
  '*.moved-aside',
  '*.pbxuser',
  '!default.pbxuser',
  '*.mode1v3',
  '!default.mode1v3',
  '*.mode2v3',
  '!default.mode2v3',
  '*.perspectivev3',
  '!default.perspectivev3',
];

const Set<String> kBinaryExtensions = {
  'png',
  'jpg',
  'jpeg',
  'gif',
  'bmp',
  'ico',
  'svg',
  'webp',
  'tiff',
  'tif',
  'mp3',
  'wav',
  'ogg',
  'flac',
  'aac',
  'm4a',
  'wma',
  'mp4',
  'avi',
  'mov',
  'wmv',
  'flv',
  'mkv',
  'webm',
  'm4v',
  'zip',
  'tar',
  'gz',
  'bz2',
  'rar',
  '7z',
  'xz',
  'tgz',
  'exe',
  'dll',
  'so',
  'dylib',
  'bin',
  'app',
  'dmg',
  'pkg',
  'deb',
  'rpm',
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'ppt',
  'pptx',
  'odt',
  'ods',
  'odp',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'class',
  'jar',
  'war',
  'ear',
  'pyc',
  'pyo',
  'db',
  'sqlite',
  'cache',
};

const Set<String> kDocumentationFileNames = {
  'readme',
  'changelog',
  'license',
  'contributing',
  'authors',
  'history',
};

const Set<String> kDocumentationExtensions = {'md', 'markdown', 'rst', 'txt'};

const Set<String> kConfigurationFileNames = {
  'pubspec.yaml',
  'package.json',
  'tsconfig.json',
  'jsconfig.json',
  'webpack.config.js',
  'babel.config.js',
  'rollup.config.js',
  'vite.config.js',
  '.eslintrc',
  '.prettierrc',
  '.editorconfig',
  'cargo.toml',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'settings.gradle',
  'cmakelists.txt',
  '.gitignore',
  '.dockerignore',
  'dockerfile',
};

const Set<String> kConfigurationExtensions = {
  'json',
  'yaml',
  'yml',
  'toml',
  'ini',
  'cfg',
  'conf',
  'config',
};

// ## 수정된 부분 ##
// main 파일 목록을 상수로 추가
const Set<String> kMainFilePatterns = {
  'main.dart',
  'main.py',
  'main.js',
  'main.ts',
  'index.js',
  'index.ts',
  'app.js',
  'app.ts',
  'server.js',
  'server.ts',
  'Main.java',
  'main.go',
  'main.rs',
  'main.c',
  'main.cpp',
  'main.swift',
  'MainActivity.kt',
  'AppDelegate.swift',
};

const int kDefaultMaxFileSize = 10 * 1024 * 1024; // 10 MB
const Duration kDefaultCacheDuration = Duration(hours: 24);
const Duration kDefaultRequestTimeout = Duration(seconds: 30);
const int kDefaultMaxConcurrentRequests = 10;
const int kDefaultMaxRetries = 3;
