const List<String> kDefaultExcludePatterns = [
  'node_modules/**',
  '.git/**',
  '.svn/**',
  '.hg/**',
  'build/**',
  'dist/**',
  'out/**',
  'target/**',
  '.dart_tool/**',
  '.pub-cache/**',
  '.gradle/**',
  '.idea/**',
  '.vscode/**',
  '*.lock',
  '*.log',
  '.DS_Store',
  'Thumbs.db',
  '__pycache__/**',
  '*.pyc',
  '.pytest_cache/**',
  'venv/**',
  'env/**',
  '.env/**',
  'coverage/**',
  '.nyc_output/**',
  'tmp/**',
  'temp/**',
  '*.min.js',
  '*.min.css',
  'package-lock.json',
  'yarn.lock',
  'Cargo.lock',
];

const Set<String> kBinaryExtensions = {
  'png',
  'jpg',
  'jpeg',
  'gif',
  'bmp',
  'ico',
  'svg',
  'webp',
  'tiff',
  'tif',
  'mp3',
  'wav',
  'ogg',
  'flac',
  'aac',
  'm4a',
  'wma',
  'mp4',
  'avi',
  'mov',
  'wmv',
  'flv',
  'mkv',
  'webm',
  'm4v',
  'zip',
  'tar',
  'gz',
  'bz2',
  'rar',
  '7z',
  'xz',
  'tgz',
  'exe',
  'dll',
  'so',
  'dylib',
  'bin',
  'app',
  'dmg',
  'pkg',
  'deb',
  'rpm',
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'ppt',
  'pptx',
  'odt',
  'ods',
  'odp',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'class',
  'jar',
  'war',
  'ear',
  'pyc',
  'pyo',
  'db',
  'sqlite',
  'cache',
};

const List<String> kConfigurationPatterns = [
  '**/*.json',
  '**/*.yaml',
  '**/*.yml',
  '**/*.toml',
  '**/*.ini',
  '**/*.cfg',
  '**/*.conf',
  '**/*.config',
  '**/.env',
  '**/.env.*',
  '**/package.json',
  '**/tsconfig.json',
  '**/jsconfig.json',
  '**/webpack.config.*',
  '**/babel.config.*',
  '**/rollup.config.*',
  '**/vite.config.*',
  '**/.eslintrc*',
  '**/.prettierrc*',
  '**/.editorconfig',
  '**/pubspec.yaml',
  '**/Cargo.toml',
  '**/go.mod',
  '**/pom.xml',
  '**/build.gradle',
  '**/settings.gradle',
  '**/CMakeLists.txt',
  '**/.gitignore',
  '**/.dockerignore',
  '**/Dockerfile',
  '**/docker-compose.*',
  '**/.gitattributes',
];

const List<String> kDocumentationPatterns = [
  '**/README*',
  '**/CHANGELOG*',
  '**/LICENSE*',
  '**/CONTRIBUTING*',
  '**/AUTHORS*',
  '**/HISTORY*',
  '**/*.md',
  '**/*.markdown',
  '**/*.rst',
  '**/*.txt',
  '**/docs/**',
  '**/doc/**',
  '**/documentation/**',
];

const int kDefaultMaxFileSize = 10 * 1024 * 1024; // 10 MB

const Duration kDefaultCacheDuration = Duration(hours: 24);

const Duration kDefaultRequestTimeout = Duration(seconds: 30);

const int kDefaultMaxConcurrentRequests = 10;

const int kDefaultMaxRetries = 3;
