// lib/src/common/constants.dart

const List<String> kDefaultExcludePatterns = [
  'node_modules/**',
  '.git/**',
  '.svn/**',
  '.hg/**',
  'build/**',
  'dist/**',
  'out/**',
  'target/**',
  '.dart_tool/**',
  '.pub-cache/**',
  '.gradle/**',
  '.idea/**',
  '.vscode/**',
  '*.lock',
  '*.log',
  '.DS_Store',
  'Thumbs.db',
  '__pycache__/**',
  '*.pyc',
  '.pytest_cache/**',
  'venv/**',
  'env/**',
  '.env/**',
  'coverage/**',
  '.nyc_output/**',
  'tmp/**',
  'temp/**',
  '*.min.js',
  '*.min.css',
  'package-lock.json',
  'yarn.lock',
  'Cargo.lock',
];

const Set<String> kBinaryExtensions = {
  'png',
  'jpg',
  'jpeg',
  'gif',
  'bmp',
  'ico',
  'svg',
  'webp',
  'tiff',
  'tif',
  'mp3',
  'wav',
  'ogg',
  'flac',
  'aac',
  'm4a',
  'wma',
  'mp4',
  'avi',
  'mov',
  'wmv',
  'flv',
  'mkv',
  'webm',
  'm4v',
  'zip',
  'tar',
  'gz',
  'bz2',
  'rar',
  '7z',
  'xz',
  'tgz',
  'exe',
  'dll',
  'so',
  'dylib',
  'bin',
  'app',
  'dmg',
  'pkg',
  'deb',
  'rpm',
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'ppt',
  'pptx',
  'odt',
  'ods',
  'odp',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'class',
  'jar',
  'war',
  'ear',
  'pyc',
  'pyo',
  'db',
  'sqlite',
  'cache',
};

const Set<String> kDocumentationFileNames = {
  'readme',
  'changelog',
  'license',
  'contributing',
  'authors',
  'history',
};

const Set<String> kDocumentationExtensions = {
  'md',
  'markdown',
  'rst',
  'txt',
};

const Set<String> kConfigurationFileNames = {
  'pubspec.yaml',
  'package.json',
  'tsconfig.json',
  'jsconfig.json',
  'webpack.config.js',
  'babel.config.js',
  'rollup.config.js',
  'vite.config.js',
  '.eslintrc',
  '.prettierrc',
  '.editorconfig',
  'cargo.toml',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'settings.gradle',
  'cmakelists.txt',
  '.gitignore',
  '.dockerignore',
  'dockerfile',
};

const Set<String> kConfigurationExtensions = {
  'json',
  'yaml',
  'yml',
  'toml',
  'ini',
  'cfg',
  'conf',
  'config',
};

// ## 수정된 부분 ##
// main 파일 목록을 상수로 추가
const Set<String> kMainFilePatterns = {
  'main.dart',
  'main.py',
  'main.js',
  'main.ts',
  'index.js',
  'index.ts',
  'app.js',
  'app.ts',
  'server.js',
  'server.ts',
  'Main.java',
  'main.go',
  'main.rs',
  'main.c',
  'main.cpp',
  'main.swift',
  'MainActivity.kt',
  'AppDelegate.swift',
};

const int kDefaultMaxFileSize = 10 * 1024 * 1024; // 10 MB
const Duration kDefaultCacheDuration = Duration(hours: 24);
const Duration kDefaultRequestTimeout = Duration(seconds: 30);
const int kDefaultMaxConcurrentRequests = 10;
const int kDefaultMaxRetries = 3;
